import test from 'node:test';
import assert from 'node:assert/strict';
import { createProofServer } from './server.mjs';
import { BookingStore, vehicles, services, classifyVehicle, priceFor } from './core.mjs';
const server=createProofServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
async function req(path,body,cookie='',headers={}){const r=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{'Content-Type':'application/json'}),Cookie:cookie,...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text}return{status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0]};}
const login=async(identity,password)=>{const r=await req('/api/login',{identity,password});assert.equal(r.status,200);return r.cookie};
try{
await test('B: five representatives and all price modes, owner override',()=>{const expected=[['mid',1800],['large',2100],['special',2500],['large',2100],['business',3000]];vehicles.forEach((v,i)=>{assert.equal(classifyVehicle(v),expected[i][0]);assert.equal(priceFor(services[0],v).amount,expected[i][1]);assert.equal(priceFor(services[1],v).amount,16500);assert.equal(priceFor(services[2],v).type,'assessment');});assert.equal(priceFor(services[0],{...vehicles[4],ownerOverrideTier:'special'}).amount,2500);});
await test('C: immutable system fields, cancelled bookings cannot resurrect',()=>{const s=new BookingStore([{id:'1'},{id:'2'}]);const b=s.request('1',{id:'forged',slotId:'2',status:'CONFIRMED'});assert.equal(b.id,'PB-001');assert.equal(b.slotId,'1');assert.equal(b.status,'PENDING');s.cancel(b.id);assert.throws(()=>s.change(b.id,'2'),/inactive/);assert.throws(()=>s.confirm(b.id),/pending/);assert.throws(()=>s.cancel(b.id),/inactive/);});
await test('F: HTTP identity matrix, plate/forged actor denied, static source blocked',async()=>{const A=await login('A','proof-a'),B=await login('B','proof-b');for(const [cookie,target,status]of [['','A',401],['','B',401],[A,'A',200],[A,'B',403],[B,'A',403],[B,'B',200]]){const r=await req(`/api/customers/${target}`,undefined,cookie);assert.equal(r.status,status);if(status!==200)assert.deepEqual(Object.keys(r.data),['error']);}assert.equal((await req('/api/customers/A?plate=TEST-A&customerId=A',undefined,'proof_session=A',{'X-Customer-Id':'A'})).status,401);assert.equal((await req('/api/login',{identity:'A',plate:'TEST-A'})).status,401);assert.equal((await req('/api/login',{identity:'toString',password:'x'})).status,401);for(const path of ['/core.mjs','/server.mjs','/tests.mjs','/../proof/core.mjs','/index.html/../core.mjs','/pos/','/warranty/'])assert.equal((await req(path)).status,404,path);const catalog=await req('/api/catalog');assert.ok(!JSON.stringify(catalog.data).includes('phoneMasked'));assert.equal((await req('/api/manage/bookings',undefined,A)).status,403);await req('/api/logout',{},A);assert.equal((await req('/api/customers/A',undefined,A)).status,401);});
await test('C/E: parallel contention, owner confirmation, quote freeze, atomic change and reopening',async()=>{const owner=await login('owner','proof-owner');const payload={slotId:'S1',vehicleId:'corolla-cross',serviceId:'wash'};const attempts=await Promise.all(Array.from({length:12},()=>req('/api/bookings',payload)));assert.equal(attempts.filter(r=>r.status===201).length,1);assert.equal(attempts.filter(r=>r.status===409).length,11);let b=attempts.find(r=>r.status===201).data;assert.equal(b.status,'PENDING');assert.equal((await req(`/api/bookings/${b.id}/confirm`,{capability:b.capability})).status,403);assert.equal((await req('/api/manage/price',{price:1900})).status,403);assert.equal((await req('/api/manage/price',{price:-1},owner)).status,400);assert.equal((await req('/api/manage/price',{price:1900},owner)).status,200);assert.equal((await req('/api/quote',payload)).data.amount,1900);assert.equal(b.quote.amount,1800);assert.equal((await req('/api/manage/slot',{slotId:'S1',open:false},owner)).status,409);const confirms=await Promise.all([req(`/api/bookings/${b.id}/confirm`,{},owner),req(`/api/bookings/${b.id}/confirm`,{},owner)]);assert.equal(confirms.filter(r=>r.status===200).length,1);const other=(await req('/api/bookings',{...payload,slotId:'S2'})).data;assert.equal((await req(`/api/bookings/${b.id}/change`,{slotId:'S2',capability:b.capability})).status,409);assert.equal((await req('/api/catalog')).data.slots[0].status,'CONFIRMED');b=(await req(`/api/bookings/${b.id}/change`,{slotId:'S3',capability:b.capability})).data;assert.equal(b.status,'PENDING');assert.equal(b.quote.amount,1800);assert.equal((await req(`/api/bookings/${b.id}/confirm`,{},owner)).status,200);assert.equal((await req(`/api/bookings/${b.id}/cancel`,{})).status,403);assert.equal((await req(`/api/bookings/${b.id}/cancel`,{capability:b.capability})).status,200);assert.equal((await req('/api/catalog')).data.slots[2].status,'OPEN');assert.equal((await req(`/api/bookings/${b.id}/change`,{slotId:'S4',capability:b.capability})).status,409);const fresh=await req('/api/bookings',{...payload,slotId:'S3'});assert.equal(fresh.status,201);assert.equal((await req('/api/manage/slot',{slotId:'S4',open:false},owner)).status,200);assert.equal((await req('/api/bookings',{...payload,slotId:'S4'})).status,409);assert.equal((await req('/api/manage/slot',{slotId:'S4',open:true},owner)).status,200);assert.equal((await req('/api/manage/vehicle',{vehicleId:'toyota-alphard',lengthMm:5010,kind:'mpv',override:'special'},owner)).status,200);assert.equal((await req('/api/quote',{vehicleId:'toyota-alphard',serviceId:'wash'})).data.amount,2500);assert.equal((await req('/api/manage/price',{price:2000},owner,{Origin:'https://attacker.example'})).status,403);const list=(await req('/api/manage/bookings',undefined,owner)).data;const confirmed=list.filter(b=>b.status==='CONFIRMED');assert.equal(new Set(confirmed.map(b=>b.slotId)).size,confirmed.length);assert.ok(!JSON.stringify(list).includes('capability'));});
}finally{await new Promise(r=>server.close(r));}
