const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(n);
const stateNames={OPEN:'可申請',PENDING:'待人員確認',CONFIRMED:'已確認',CANCELLED:'已取消',CLOSED:'暫停開放'};
let catalog, currentBooking, timer;
async function api(path,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(`${r.status} · ${d.error}`);return d;}
function toast(text){$('#toast').textContent=text;clearTimeout(timer);timer=setTimeout(()=>$('#toast').textContent='',6000);}
function action(fn){return async e=>{e?.preventDefault();try{await fn(e);}catch(error){toast(error.message);}};}
function options(el,rows,label){const old=el.value;el.replaceChildren(...rows.map(x=>new Option(label(x),x.id)));if(rows.some(x=>x.id===old))el.value=old;}
async function refresh(){catalog=await api('/api/catalog');options($('#service'),catalog.services,x=>x.name);options($('#vehicle'),catalog.vehicles,x=>`${x.brand} ${x.model}`);options($('#adminVehicle'),catalog.vehicles,x=>`${x.brand} ${x.model}`);options($('#adminSlot'),catalog.slots,x=>`${x.date} ${x.time} · ${stateNames[x.status]}`);$('#adminPrice').value=catalog.services[0].prices.mid;$('#session').textContent=`目前身分：${catalog.actor.type==='customer'?'Customer '+catalog.actor.customerId:catalog.actor.type==='owner'?'Owner':'Public'}`;vehicleFields();renderSlots();await renderPrice();}
async function renderPrice(){const q=await api('/api/quote',{vehicleId:$('#vehicle').value,serviceId:$('#service').value});const box=$('#price');box.replaceChildren();const tier=document.createElement('div');tier.className='small muted';tier.textContent=catalog.tierLabels[q.tier]+' · 基準價格';const amount=document.createElement('div');amount.className='amount';amount.textContent=q.type==='amount'?money(q.amount):'現場評估';const note=document.createElement('p');note.className='small muted';note.textContent=q.note;box.append(tier,amount,note);$('#rule').textContent=`自動分類：${catalog.tierLabels[q.autoTier]}${catalog.vehicles.find(x=>x.id===$('#vehicle').value).ownerOverrideTier?' → Owner 指定：'+catalog.tierLabels[q.tier]:''}`;}
function renderSlots(){const box=$('#slots');box.replaceChildren();for(const slot of catalog.slots){const b=document.createElement('button');b.className='slot';b.disabled=slot.status!=='OPEN';const title=document.createElement('b');title.textContent=`${slot.date.slice(5).replace('-','/')} ${slot.time}`;const status=document.createElement('small');status.textContent=stateNames[slot.status];b.append(title,status);b.onclick=action(async()=>{if(currentBooking && currentBooking.status!=='CANCELLED')throw Error('已有預約需求，請使用改期或取消。');currentBooking=await api('/api/bookings',{slotId:slot.id,vehicleId:$('#vehicle').value,serviceId:$('#service').value});await refresh();renderBooking();});box.append(b);}}
function summaryText(b){const slot=catalog.slots.find(s=>s.id===b.slotId);return `【ZERO Proof 合成預約需求・請勿正式送出】\n編號：${b.id}\n服務：${b.serviceName}\n車款：${b.vehicleName}\n分類：${catalog.tierLabels[b.quote.tier]}\n送出時基準價：${b.quote.type==='amount'?money(b.quote.amount):'現場評估'}\n時段：${slot.date} ${slot.time}\n狀態：${stateNames[b.status]} (${b.status})\n網站申請不代表正式預約，仍需人員確認。`;}
function renderBooking(){const b=currentBooking,box=$('#summary');box.innerHTML='<h3>你的預約摘要</h3>';const status=document.createElement('span');status.className='status';status.textContent=stateNames[b.status];const ta=document.createElement('textarea');ta.rows=9;ta.readOnly=true;ta.setAttribute('aria-label','LINE 預約摘要');ta.value=summaryText(b);const history=document.createElement('p');history.className='small muted';history.textContent=b.history.join(' → ');box.append(status,history,ta);const note=document.createElement('p');note.className='small muted';note.textContent='金額保留送出時的基準價。LINE 短連結不會自動帶入文字：先複製摘要，再開啟 LINE 貼上。';box.append(note);const actions=document.createElement('div');actions.className='actions';const copy=document.createElement('button');copy.className='btn primary';copy.textContent='1. 複製預約摘要';copy.onclick=action(async()=>{await navigator.clipboard.writeText(ta.value);toast('摘要已複製。Proof 請勿正式送出。');});const line=document.createElement('a');line.className='btn';line.href='https://lin.ee/y8kjBXa';line.target='_blank';line.rel='noopener';line.textContent='2. 開啟官方 LINE ↗';actions.append(copy,line);box.append(actions);if(b.status==='CANCELLED')return;const label=document.createElement('label');label.textContent='改期至';const changeSelect=document.createElement('select');changeSelect.id='changeSlot';options(changeSelect,catalog.slots.filter(s=>s.status==='OPEN'),s=>`${s.date} ${s.time}`);label.append(changeSelect);box.append(label);const change=document.createElement('button');change.className='btn';change.textContent='申請改期';change.disabled=!changeSelect.options.length;change.onclick=action(async()=>{currentBooking=await api(`/api/bookings/${b.id}/change`,{slotId:changeSelect.value,capability:b.capability});await refresh();renderBooking();});const cancel=document.createElement('button');cancel.className='btn';cancel.textContent='取消這筆需求';cancel.onclick=action(async()=>{currentBooking=await api(`/api/bookings/${b.id}/cancel`,{capability:b.capability});await refresh();renderBooking();});const end=document.createElement('div');end.className='actions';end.append(change,cancel);box.append(end);}
function vehicleFields(){const v=catalog.vehicles.find(x=>x.id===$('#adminVehicle').value);$('#lengthMm').value=v.lengthMm;$('#kind').value=v.kind;$('#override').value=v.ownerOverrideTier||'';}
async function managed(path,body,message){await api(path,body);await refresh();$('#adminStatus').textContent=message;toast(message);}
$('#service').onchange=$('#vehicle').onchange=action(renderPrice);
for(const el of document.querySelectorAll('[data-service]'))el.onclick=action(async()=>{$('#service').value=el.dataset.service;await renderPrice();location.hash='pricing';});
$('#adminVehicle').onchange=vehicleFields;
$('#savePrice').onclick=action(()=>managed('/api/manage/price',{price:Number($('#adminPrice').value)},'價格已儲存；既有預約基準價不變。'));
$('#saveSlot').onclick=action(()=>managed('/api/manage/slot',{slotId:$('#adminSlot').value,open:$('#slotOpen').value==='true'},'時段狀態已儲存。'));
$('#saveVehicle').onclick=action(()=>managed('/api/manage/vehicle',{vehicleId:$('#adminVehicle').value,lengthMm:Number($('#lengthMm').value),kind:$('#kind').value,override:$('#override').value},'車輛資料已儲存，價格分類已更新。'));
async function clearPrivate(){catalog=null;$('#profile').replaceChildren();$('#security').textContent='身分已變更，先前資料已清除。';$('#bookingList').replaceChildren();await refresh();}
$('#identity').onchange=()=>$('#password').value=$('#identity').value==='A'?'proof-a':'proof-b';
$('#customerLogin').onsubmit=action(async()=>{await api('/api/login',{identity:$('#identity').value,password:$('#password').value});await clearPrivate();const customer=await api(`/api/customers/${catalog.actor.customerId}`);const box=$('#profile');const title=document.createElement('h3');title.textContent=customer.displayName;const warranty=document.createElement('p');warranty.className='small muted';warranty.textContent=customer.warranty;box.append(title,warranty);for(const name of customer.vehicles){const v=catalog.vehicles.find(x=>`${x.brand} ${x.model}`===name);if(!v)continue;const b=document.createElement('button');b.className='btn';b.textContent=`用 ${name} 預約`;b.onclick=action(async()=>{$('#vehicle').value=v.id;await renderPrice();location.hash='booking';});box.append(b);}toast('已登入，選已儲存車輛即可預約。');});
async function logout(){await api('/api/logout',{});await clearPrivate();}
$('#logout').onclick=$('#publicPersona').onclick=action(logout);
$('#ownerLogin').onclick=action(async()=>{await api('/api/login',{identity:'owner',password:'proof-owner'});await clearPrivate();await bookingList();toast('已進入本機 Owner 測試身分。');});
async function bookingList(){const rows=await api('/api/manage/bookings');const box=$('#bookingList');box.replaceChildren();if(!rows.length)box.textContent='尚無預約需求。';for(const b of rows){const row=document.createElement('div');row.className='bookingrow';const info=document.createElement('p');info.textContent=`${b.id} · ${b.vehicleName} · ${b.slotId} · ${stateNames[b.status]} · ${b.quote.type==='amount'?money(b.quote.amount):'現場評估'}`;row.append(info);if(b.status==='PENDING'){const confirm=document.createElement('button');confirm.className='btn primary';confirm.textContent=`確認 ${b.id}`;confirm.onclick=action(async()=>{const next=await api(`/api/bookings/${b.id}/confirm`,{});if(currentBooking?.id===b.id)currentBooking=next;await refresh();if(currentBooking)renderBooking();await bookingList();});row.append(confirm);}if(['PENDING','CONFIRMED'].includes(b.status)){const cancel=document.createElement('button');cancel.className='btn';cancel.textContent='取消 '+b.id;cancel.onclick=action(async()=>{const next=await api('/api/bookings/'+b.id+'/cancel',{});if(currentBooking?.id===b.id)currentBooking=next;await refresh();if(currentBooking)renderBooking();await bookingList();});row.append(cancel);}box.append(row);}}
$('#refreshBookings').onclick=action(bookingList);
for(const b of document.querySelectorAll('[data-target]'))b.onclick=async()=>{try{$('#security').textContent=JSON.stringify(await api(`/api/customers/${b.dataset.target}`),null,2);}catch(e){$('#security').textContent=`ACCESS DENIED — ${e.message}`;}};
await refresh();
