import assert from 'node:assert/strict';
import { vehicles, services, classifyVehicle, priceFor, BookingStore, readPrivateCustomer } from './core.mjs';
const byId = (id) => vehicles.find((v) => v.id === id);
const service = (id) => services.find((s) => s.id === id);
assert.equal(classifyVehicle(byId('corolla-cross')), 'mid');
assert.equal(classifyVehicle(byId('lexus-nx')), 'large');
assert.equal(classifyVehicle(byId('porsche-cayenne')), 'special');
assert.equal(classifyVehicle(byId('tesla-model-y')), 'large');
assert.equal(classifyVehicle(byId('toyota-alphard'), false), 'business');
assert.equal(priceFor(service('wash'), byId('corolla-cross')).amount, 1800);
assert.equal(priceFor(service('wash'), byId('lexus-nx')).amount, 2100);
assert.equal(priceFor(service('wash'), byId('porsche-cayenne')).amount, 2500);
assert.equal(priceFor(service('wash'), byId('toyota-alphard')).amount, 3000);
assert.equal(priceFor(service('paint-coating'), byId('porsche-cayenne')).amount, 16500);
assert.equal(priceFor(service('correction'), byId('porsche-cayenne')).type, 'assessment');
const store = new BookingStore([{ id: 's1' }, { id: 's2' }]);
const b1 = store.request('s1', { customer: 'Synthetic A' });
assert.equal(b1.status, 'PENDING');
store.confirm(b1.id);
assert.throws(() => store.request('s1', { customer: 'Synthetic B' }), /slot not open/);
store.change(b1.id, 's2');
store.confirm(b1.id);
store.cancel(b1.id);
assert.equal(store.slots[1].status, 'OPEN');
assert.throws(() => readPrivateCustomer({ type: 'anonymous' }, 'A'), /AUTH_REQUIRED/);
assert.throws(() => readPrivateCustomer({ type: 'customer', customerId: 'A' }, 'B'), /FORBIDDEN/);
assert.throws(() => readPrivateCustomer({ type: 'customer', customerId: 'B' }, 'A'), /FORBIDDEN/);
assert.equal(readPrivateCustomer({ type: 'customer', customerId: 'A' }, 'A').id, 'A');
console.log('PASS — Product & Technical Proof R1 core invariants');
